# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c492b573427d1afeb38de19895341b96aa90eff9851c9492ca34c25fb4c0edfdaa5e1f9d4da5c9c68a5cd63a7de7050a22a70a9643ce360336d686dd7ce96af2

test:
  secret_key_base: 22997e4f0c3a5435cfe56e9970a17b0c64b5562ca6b50269905e4e630c4338336d7a4131640845d00afc1e838c9238d898a50eb3b11d451d89c1b7773fc21e71

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
